version: '3.9'
services:
  scary_java_app:
    build: scary_java_app
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - log_drive:/app/logs
  log_parser:
    build: log_parser
    restart: always
    volumes:
      - log_drive:/app/logs
    depends_on: 
      - scary_java_app
volumes:
  log_drive: